[sema] NFC Unable to build Sema library with MSVC Debug target due to missing /bigobj
Summary:
Unable to build sema library on MSVC with Debug target

```
C:\clang\llvm-project\clang\lib\Sema\SemaOpenMP.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
```

Reviewed By: aaron.ballman

Subscribers: mgorny, cfe-commits

Tags: #clang

Differential Revision: https://reviews.llvm.org/D79292

llvm-monorepo: 9e194a3b9356c6ef0498609c1779043d1b6bb9e1